### ISSUE TITLE
poster glitch on lispector book page - please help?

### ISSUE THREAD

**Issue by ndbooks** [sonnetmedia/www.ndbooks.com#52]
Hi Bud, 

I've tried to do it from the original pages but no luck

http://www.ndbooks.com/author/clarice-lispector/

![lispector 1](https://cloud.githubusercontent.com/assets/10980123/7936951/ed01a2c4-090a-11e5-9cab-c2c7fc4e643f.jpg)

**Comment by budparr** [comment]
Sorry, but I'm wondering if you can be more specific. I'm not certain about what you're trying to achieve.
