### ISSUE TITLE
Why isn't the feature image on homepage updating?

### ISSUE THREAD

**Issue by ndbooks** [sonnetmedia/www.ndbooks.com#56]
I tried to make it this: 
![mirages higher res](https://cloud.githubusercontent.com/assets/10980123/8163608/1c26dfc8-1352-11e5-9f57-ed5c1f634b24.jpg)

**Comment by budparr** [comment]
I assume you mean the featured image field at the top of the entry screen. 

Two things. I haven't set up the page to use that as part of its layout. It would work with the floaty box thingy. 

And two, that image would work. It's the wrong aspect ratio. Needs to be 16x9.

If you're ready to change the layout style of the home page we can talk about that and make it happen.

**Comment by ndbooks** [comment]
Yes I mean the featured image field at the top. Do you mean it WOULDN'T work with the floaty box thing or that it WOULD? Sorry... 

I can get the image fixed by Tynan. Then can we make it work?

**Comment by budparr** [comment]
Well the floaty boxes are one layout. Using a featured image is another. They don't really go together. But it shouldn't take too much to change it (since I designed it to be changeable - I just left that function in a state of not quite completeness).




Send me the image when you've got it fixed up.

**Comment by ndbooks** [comment]
![eyes](https://cloud.githubusercontent.com/assets/10980123/8164362/914e8a68-1356-11e5-99c9-02fcfb9668c3.jpg)

Will this work?

**Comment by budparr** [comment]
Ill have to look when I'm at my computer. I'm sitting in a coffee shop on 8th street trying to avoid using my computer

**Comment by ndbooks** [comment]
okay! have a latte for me

**Comment by budparr** [comment]
Cold brew coffee. They have it on tap here!

**Comment by budparr** [comment]
This might work. It doesn't appear to be 16x9 though.

**Comment by budparr** [comment]
and no copy on it? It looks a little, eh, strange, with just eyeballs and no copy.

**Comment by ndbooks** [comment]
really it says so in my finder and Tynan whipped it up...

On Mon, Jun 15, 2015 at 3:09 PM, Bud Parr <notifications@github.com> wrote:

> This might work. It doesn't appear to be 16x9 though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/56#issuecomment-112177023>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by ndbooks** [comment]
we could also use a file with copy but I thought it was cool without...
does it look weird?

On Mon, Jun 15, 2015 at 3:11 PM, Chew, Mieke <mchew@ndbooks.com> wrote:

> really it says so in my finder and Tynan whipped it up...
>
> On Mon, Jun 15, 2015 at 3:09 PM, Bud Parr <notifications@github.com>
> wrote:
>
>> This might work. It doesn't appear to be 16x9 though.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/newdirections/www.ndbooks.com/issues/56#issuecomment-112177023>
>> .
>>
>
>
>
> --
> Mieke Chew
> New Directions Publishing
> 80 8th Avenue
> New York, NY, 10011
> (212-255-0230)
> mchew@ndbooks.com
>
> ndbooks.com
> twitter.com/newdirections
> facebook.com/ndbooks
>
>


-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
It's 1600x1900, not 1600x900. 

Not sure. I mean it will need copy in some form or another, lest people do a wtf when the get to the site, but once I get the layout set up we can worry about that, so I'll work with it without copy at first.

**Comment by ndbooks** [comment]
Tynan says the image won't work 1600 x 1900... unless you have a brilliant idea/?????

**Comment by budparr** [comment]
Not following you. It's 1600x1900 now. That's nearly square - doesn't really work. 

I realize that the eyeballs are interesting as a backdrop but when the image is really large, they're just freaky.

**Comment by ndbooks** [comment]
No I mean the cover WITH the title doesn't work in those dimensions. You
follow? Sorry I have been going back and forth on this with Tynan for
hours. Attached is a BIG file that maybe you know a trick for that we can
then learn from you??? I don't know..

On Mon, Jun 15, 2015 at 4:43 PM, Bud Parr <notifications@github.com> wrote:

> Not following you. It's 1600x1900 now. That's nearly square - doesn't
> really work.
>
> I realize that the eyeballs are interesting as a backdrop but when the
> image is really large, they're just freaky.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/56#issuecomment-112205047>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
not seeing the file, but just to be clear:
what we want is 1600 x 900,
NOT
1600 x 1900

**Comment by ndbooks** [comment]
Dear Bud, 
I thought I wrote you back on this. Is there anything we can do with this file? Or do we just stick with the current layout for now? I really want to make a big to-do of this book and the cover is so goooood....

**Comment by ndbooks** [comment]
![mirages higher res](https://cloud.githubusercontent.com/assets/10980123/8186769/3c5bf486-141a-11e5-9ec4-42675f60b2d3.jpg)

**Comment by budparr** [comment]
You're not able to make it 1600x 900?

**Comment by ndbooks** [comment]
Not unless you have an idea...

**Comment by budparr** [comment]
I don't, but let me stew on it. When is the book launch?

**Comment by ndbooks** [comment]
July 9th I think... but it hasn't gotten much love..

On Tue, Jun 16, 2015 at 11:49 AM, Bud Parr <notifications@github.com> wrote:

> I don't, but let me stew on it. When is the book launch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/56#issuecomment-112476900>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks
