### ISSUE TITLE
Please make it so only authors or books come up as options on homepage "relationship" tab

### ISSUE THREAD

**Issue by ndbooks** [sonnetmedia/www.ndbooks.com#57]
It's really excruciating trying to scroll through all the blurbs which can't be linked to homepage content anyway. THANKS BUD!

**Comment by budparr** [comment]
let me think how best to do this. To exclude any one section means to make a separate field for each section we can link to. Perhaps it would be better just to give you a place to put in a slug (the part of the page's URL after ndbooks.com), rather than create a relationship. What thinkye?
