### ISSUE TITLE
Need to create a page for an entire CD of OPPEN poems

### ISSUE THREAD

**Issue by ndbooks** [sonnetmedia/www.ndbooks.com#58]
How best to go about? 

Before we figure it out, though, Erik needs us to decide on a URL to print in the book.

**Comment by budparr** [comment]
Our initial idea on this was to put stuff in an article (blog) and link to it. That gives a lot of flexibility and serves to promote it (being on the blog) 

so the URL would be: http://www.ndbooks.com/article/oppen-poems (or whatever you title it as a slug)

We could do a standalone page, but I'd caution against doing too much of that as it can get unwieldy from an organizational standpoint, which is also why I prefer using an article. It would be in the pages section. And, like as as an article the URL would essentially just be a slug of the title you create.
All the other pages are here: http://www.ndbooks.com/cms#/wh/content/pages
