### ISSUE TITLE
banner question - thoughts?

### ISSUE THREAD

**Issue by ndbooks** [sonnetmedia/www.ndbooks.com#59]
Can we ask Bud banner images for blog posts? They look too lo-fi, pixellated, and degraded. I know the images have to be something like 1500 pixels wide, 72 dpi, but even when I've supplied that for you, they come through crunched. 

Maybe the whole way the banner operates needs a tweak. It's a higher res image that seems to be required than is typically passed around the web.

**Comment by budparr** [comment]
Can you send me an example, please, along with, separately, the file you uploaded as well as the original that it came from?
