### ISSUE TITLE
still can't share link with featured image on facebook from site

### ISSUE THREAD

**Issue by ndbooks** [sonnetmedia/www.ndbooks.com#62]

**Comment by budparr** [comment]
can you give me an example, please?

**Comment by ndbooks** [comment]
yes tried to share the Middleton blog post of facebook and the image
wouldn't come up. we've talked about before. I remember you said you were
on it but that it was easier said than done.

On Tue, Dec 1, 2015 at 3:27 PM, Bud Parr <notifications@github.com> wrote:

> can you give me an example, please?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sonnetmedia/www.ndbooks.com/issues/62#issuecomment-161085774>
> .
>



-- 

Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
This is what I'm getting. Not you?

<img width="504" alt="screen shot 2015-12-01 at 3 41 40 pm" src="https://cloud.githubusercontent.com/assets/115347/11513595/14bd35a0-9842-11e5-8507-2bb887eb273c.png">

**Comment by ndbooks** [comment]
No! didn't work for me. God. This is like when I help my Mum with "the
computer". Sorry Bud. I don't know why it wasn't doing it for me.

On Tue, Dec 1, 2015 at 3:42 PM, Bud Parr <notifications@github.com> wrote:

> This is what I'm getting. Not you?
>
> [image: screen shot 2015-12-01 at 3 41 40 pm]
> <https://cloud.githubusercontent.com/assets/115347/11513595/14bd35a0-9842-11e5-8507-2bb887eb273c.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sonnetmedia/www.ndbooks.com/issues/62#issuecomment-161089425>
> .
>



-- 

Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
No, it's not your fault. It's definitely something I've screwed up there. I can fix it, but not until Thursday, if that's okay. (I'm giving a presentation Wed. night in front of about 80 people who know more than me about what I'm presenting about, so I'm freaking out preparing until then). 

You should be able to add the image manually, if you want, or I'll share it and you can re-share it (I think I'm "friends" with ndbooks on FB).
