### ISSUE TITLE
Books not all appearing on New and Forthcoming page

### ISSUE THREAD

**Issue by ndbooks** [sonnetmedia/www.ndbooks.com#63]
Dear Bud, 
There are more forthcoming books than this. Why doesn't it just fill the grid with a full three or four rows of titles? 
http://www.ndbooks.com/books/

**Comment by budparr** [comment]
about how many should be there?

**Comment by ndbooks** [comment]
There are enough to make four rows.

On Mon, Dec 7, 2015 at 4:57 PM, Bud Parr <notifications@github.com> wrote:

> about how many should be there?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sonnetmedia/www.ndbooks.com/issues/63#issuecomment-162678180>
> .
>



-- 

Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
okay. I'm just wrapping up some of the shop stuff and will check it out right after.

**Comment by ndbooks** [comment]
cool. it's not urgent at all.

On Mon, Dec 7, 2015 at 5:02 PM, Bud Parr <notifications@github.com> wrote:

> okay. I'm just wrapping up some of the shop stuff and will check it out
> right after.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sonnetmedia/www.ndbooks.com/issues/63#issuecomment-162679884>
> .
>



-- 

Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
Can you give me an example of a book or books that should be showing there, but are not?

Thanks!

**Comment by ndbooks** [comment]
Missing:
LOOKING AT PICTURES Nov
TROPISMS Nov
BECAUSE SHE NEVER ASKED Nov
QUARRY and BIRTH-MARK by Howe pubs on 12/9/15
ALL THE POEMS by Stevie Smith pubs on 2/22/16
A LITTLE LUMPEN NOVELITA by Bolano (pbk) pubs on 3/21/16
EXTRACTING THE STONE.. by Pizarnik pubs on 3/28/16
YELLOW SOFA by Queiros 04/18/16
ONCE AND FOR ALL by SChwartz 4/18/16

This would fill the 9 gaps to make four full rows.

How does it fill? Would be good if it showed the books that came out the
month before and then filled from there. What do you think?

MC


On Tue, Dec 8, 2015 at 8:25 AM, Bud Parr <notifications@github.com> wrote:

> Can you give me an example of a book or books that should be showing
> there, but are not?
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sonnetmedia/www.ndbooks.com/issues/63#issuecomment-162878967>
> .
>



-- 

Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
I believe I fixed this (I didn't look at the particular books, so if you could have a glance). 

Also, this book needs a pub date: http://www.ndbooks.com/cms#/wh/content/book/-K1Awk5JhI9uGLuyiWqK

**Comment by ndbooks** [comment]
Thanks!!

On Wed, Dec 9, 2015 at 9:01 AM, Bud Parr <notifications@github.com> wrote:

> I believe I fixed this (I didn't look at the particular books, so if you
> could have a glance).
>
> Also, this book needs a pub date:
> http://www.ndbooks.com/cms#/wh/content/book/-K1Awk5JhI9uGLuyiWqK
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sonnetmedia/www.ndbooks.com/issues/63#issuecomment-163245893>
> .
>



-- 

Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks
