### ISSUE TITLE
Homepage glitch

### ISSUE THREAD

**Issue by ndbooks** [sonnetmedia/www.ndbooks.com#64]
Dear Bud, 
I took screenshots of the problem I am having with finding the book or author or page I want to make the "related" entry for the homepage. It's terribly annoying. Would be so good to change to URL copy paste.

**Comment by ndbooks** [comment]
![screen shot 2015-12-08 at 11 58 30 am](https://cloud.githubusercontent.com/assets/10980123/11693388/a2c726fe-9e72-11e5-9f2e-3ac5e059292f.png)
![screen shot 2015-12-08 at 12 00 15 pm](https://cloud.githubusercontent.com/assets/10980123/11693385/a2c41644-9e72-11e5-9766-80094eba8d14.png)
![screen shot 2015-12-08 at 12 00 39 pm](https://cloud.githubusercontent.com/assets/10980123/11693387/a2c6326c-9e72-11e5-9908-245bd6a71826.png)

**Comment by ndbooks** [comment]
Thanks Bud! No rush!
Shop page looks great.

On Wed, Dec 9, 2015 at 12:50 PM, Bud Parr <notifications@github.com> wrote:

> Yeah, this is what we talked about, right? Just making sure. I'm on it.
> The shopping thing took a while, but I'll chip away at these things now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sonnetmedia/www.ndbooks.com/issues/64#issuecomment-163337858>
> .
>



-- 

Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
This is fixed. I'm going to remove the old relationship field in a moment. Now you'll just copy and paste the link you want.
