### ISSUE TITLE
Editor not showing up on ONCE AND FOR ALL bookpage

### ISSUE THREAD

**Issue by ndbooks** [sonnetmedia/www.ndbooks.com#65]
dear bud, 
long time no github!
Craig Morgan Teicher, the editor of ONCE AND FOR ALL: BEST OF DELMORE SCHWARTZ, isn't showing up on the book page... http://www.ndbooks.com/book/once-and-for-all-the-best-of-delmore-schwartz/
Please help. He will be cross/depressed. 
thanks!

**Comment by budparr** [comment]
Hiya - Looks like it's there:
<img width="727" alt="screen shot 2016-02-08 at 6 16 25 pm" src="https://cloud.githubusercontent.com/assets/115347/12902587/17eb0af2-ce90-11e5-842c-47b797ae114a.png">

**Comment by ndbooks** [comment]
thanks bud!

On Mon, Feb 8, 2016 at 6:16 PM, Bud Parr <notifications@github.com> wrote:

> Hiya - Looks like it's there:
> [image: screen shot 2016-02-08 at 6 16 25 pm]
> <https://cloud.githubusercontent.com/assets/115347/12902587/17eb0af2-ce90-11e5-842c-47b797ae114a.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sonnetmedia/www.ndbooks.com/issues/65#issuecomment-181615923>
> .
>



-- 

Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks
