### ISSUE TITLE
Change "New and Forthcoming Books" to show books release in last 2 months

### ISSUE THREAD

**Issue by ndbooks** [sonnetmedia/www.ndbooks.com#66]
Dear Bud, 
Can we please change the way the New and Forthcoming books lists generates? It would be great for the books to start with books that were published 2 months through till forthcoming. 
If this is something I can do on my end, just let me know. Thanks! 
MC

**Comment by budparr** [comment]
I'll have a look.

**Comment by ndbooks** [comment]
thanks bud!

On Mon, Apr 25, 2016 at 1:46 PM, Bud Parr <notifications@github.com> wrote:

> I'll have a look.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sonnetmedia/www.ndbooks.com/issues/66#issuecomment-214457357>
>



-- 

Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
So I made a fix on this. It's not exactly the dates you wanted, but there are more books now. I'll work on a longer term solution (the way I initially coded it was kinda funky), but wanted to get something up for you now.
