### ISSUE TITLE
website is all out of whack! 

### ISSUE THREAD

**Issue by ndbooks** [sonnetmedia/www.ndbooks.com#68]
did I do something bad...? 
![screen shot 2016-05-24 at 12 18 22 pm](https://cloud.githubusercontent.com/assets/10980123/15511475/acf6497e-21a9-11e6-973d-2f1d3482373b.png)

**Comment by budparr** [comment]
that's weird. seems to be okay now, for me. Is it for you?

**Comment by ndbooks** [comment]
it's back! phewf


On Tue, May 24, 2016 at 1:04 PM, Bud Parr <notifications@github.com> wrote:

> that's weird. seems to be okay now, for me. Is it for you?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sonnetmedia/www.ndbooks.com/issues/68#issuecomment-221337350>
>



-- 

Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks
